package de.dhbw.wwi13b.shared.util;

/**
 * Created by j on 8/22/16.
 */
public enum Joint {
    HEADJAW,
    HEADPITCH,
    LSHOULDERPITCH,
    HEADYAW,
    LSHOULDERROLL,
    LELBOWYAW,
    LELBOWROLL,
    LWRISTYAW,
    LHAND,
    LHIPYAWPITCH,
    LHIPROLL,
    LHIPPITCH,
    LKNEEPITCH,
    LANKLEPITCH,
    LANKLEROLL,
    RHIPYAWPITCH,
    RHIPROLL,
    RHIPPITCH,
    RKNEEPITCH,
    RANKLEPITCH,
    RANKLEROLL,
    RSHOULDERPITCH,
    RSHOULDERROLL,
    RELBOWYAW,
    RELBOWROLL,
    RWRISTYAW,
    RHAND
}
